apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ${secretName}
  namespace: ${secretNamespace}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: ${clusterSecretStore}
  target:
    template: 
      type: "${secretType}"
      engine: v2
      data:
  %{~ for k,v in secretTemplate ~}
        ${k}: ${v}
  %{ endfor ~}
  name: ${secretName}
  data: 
  %{~ for k,v in secretDataRef ~}
    - secretKey: ${k}
      remoteRef: 
        key: ${v}
  %{ endfor }